package com.endexpansion.registry;

import com.endexpansion.EndExpansion;
import com.endexpansion.block.EnderTeleporterBlock;
import com.endexpansion.block.VoidAnchorBlock;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public final class EndBlocks {
        public static Block ENDER_STONE;
    public static Block ENDER_SOIL;
    public static Block ENDER_GRASS;
    public static Block ENDER_MOSS;
    public static Block ENDER_MUD;
    public static Block ENDER_ROCK;
    public static Block ENDER_BRICKS;
    public static Block ENDER_TILES;
    public static Block CRACKED_ENDER_BRICKS;
    public static Block POLISHED_ENDER_STONE;
    public static Block ENDER_STONE_PILLAR;
    public static Block ENDER_STONE_SLAB;
    public static Block ENDER_STONE_STAIRS;
    public static Block ENDER_STONE_WALL;
    public static Block ENDER_LOG;
    public static Block STRIPPED_ENDER_LOG;
    public static Block ENDER_WOOD;
    public static Block STRIPPED_ENDER_WOOD;
    public static Block ENDER_PLANKS;
    public static Block ENDER_LEAVES;
    public static Block ENDER_SAPLING;
    public static Block ENDER_STAIRS;
    public static Block ENDER_SLAB;
    public static Block ENDER_FENCE;
    public static Block ENDER_FENCE_GATE;
    public static Block ENDER_DOOR;
    public static Block ENDER_TRAPDOOR;
    public static Block ENDER_BUTTON;
    public static Block ENDER_PRESSURE_PLATE;
    public static Block ENDER_SIGN;
    public static Block ENDER_HANGING_SIGN;
    public static Block END_CRYSTAL_BLOCK;
    public static Block CRYSTAL_GLASS;
    public static Block CRYSTAL_BRICKS;
    public static Block CRYSTAL_PILLAR;
    public static Block CRYSTAL_LAMP;
    public static Block CRYSTAL_CLUSTER;
    public static Block VOID_STONE;
    public static Block VOID_BRICKS;
    public static Block VOID_TILES;
    public static Block VOID_PILLAR;
    public static Block VOID_GLASS;
    public static Block VOID_LAMP;
    public static Block ENDERITE_ORE;
    public static Block RAW_ENDERITE_BLOCK;
    public static Block ENDERITE_BLOCK;
    public static Block VOID_ANCHOR;
    public static Block ENDER_TELEPORTER;
    private static Identifier id(String path) { return new Identifier(EndExpansion.MOD_ID, path); }
    public static void register() {
        ENDER_STONE = Registry.register(Registries.BLOCK, id("ender_stone"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_SOIL = Registry.register(Registries.BLOCK, id("ender_soil"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_GRASS = Registry.register(Registries.BLOCK, id("ender_grass"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_MOSS = Registry.register(Registries.BLOCK, id("ender_moss"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_MUD = Registry.register(Registries.BLOCK, id("ender_mud"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_ROCK = Registry.register(Registries.BLOCK, id("ender_rock"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_BRICKS = Registry.register(Registries.BLOCK, id("ender_bricks"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_TILES = Registry.register(Registries.BLOCK, id("ender_tiles"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        CRACKED_ENDER_BRICKS = Registry.register(Registries.BLOCK, id("cracked_ender_bricks"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        POLISHED_ENDER_STONE = Registry.register(Registries.BLOCK, id("polished_ender_stone"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_STONE_PILLAR = Registry.register(Registries.BLOCK, id("ender_stone_pillar"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_STONE_SLAB = Registry.register(Registries.BLOCK, id("ender_stone_slab"), new SlabBlock(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2, 6)));
        ENDER_STONE_STAIRS = Registry.register(Registries.BLOCK, id("ender_stone_stairs"), new StairsBlock(Blocks.END_STONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.END_STONE)));
        ENDER_STONE_WALL = Registry.register(Registries.BLOCK, id("ender_stone_wall"), new WallBlock(FabricBlockSettings.copyOf(Blocks.END_STONE)));
        ENDER_LOG = Registry.register(Registries.BLOCK, id("ender_log"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        STRIPPED_ENDER_LOG = Registry.register(Registries.BLOCK, id("stripped_ender_log"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_WOOD = Registry.register(Registries.BLOCK, id("ender_wood"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        STRIPPED_ENDER_WOOD = Registry.register(Registries.BLOCK, id("stripped_ender_wood"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_PLANKS = Registry.register(Registries.BLOCK, id("ender_planks"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDER_LEAVES = Registry.register(Registries.BLOCK, id("ender_leaves"), new LeavesBlock(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).strength(0.2f).luminance(2)));
        ENDER_SAPLING = Registry.register(Registries.BLOCK, id("ender_sapling"), new Block(FabricBlockSettings.copyOf(Blocks.OAK_SAPLING).noCollision().breakInstantly()));
        ENDER_STAIRS = Registry.register(Registries.BLOCK, id("ender_stairs"), new StairsBlock(Blocks.END_STONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.END_STONE)));
        ENDER_SLAB = Registry.register(Registries.BLOCK, id("ender_slab"), new SlabBlock(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2, 6)));
        ENDER_FENCE = Registry.register(Registries.BLOCK, id("ender_fence"), new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS)));
        ENDER_FENCE_GATE = Registry.register(Registries.BLOCK, id("ender_fence_gate"), new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS)));
        ENDER_DOOR = Registry.register(Registries.BLOCK, id("ender_door"), new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS).nonOpaque(), BlockSetType.OAK));
        ENDER_TRAPDOOR = Registry.register(Registries.BLOCK, id("ender_trapdoor"), new TrapdoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS).nonOpaque(), BlockSetType.OAK));
        ENDER_BUTTON = Registry.register(Registries.BLOCK, id("ender_button"), new ButtonBlock(FabricBlockSettings.copyOf(Blocks.STONE), BlockSetType.STONE, 20, false));
        ENDER_SIGN = Registry.register(Registries.BLOCK, id("ender_sign"), new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS).strength(1)));
        ENDER_HANGING_SIGN = Registry.register(Registries.BLOCK, id("ender_hanging_sign"), new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS).strength(1)));
        ENDER_PRESSURE_PLATE = Registry.register(Registries.BLOCK, id("ender_pressure_plate"), new PressurePlateBlock(PressurePlateBlock.ActivationRule.EVERYTHING, FabricBlockSettings.copyOf(Blocks.STONE), BlockSetType.STONE));
        END_CRYSTAL_BLOCK = Registry.register(Registries.BLOCK, id("end_crystal_block"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(10)));
        CRYSTAL_GLASS = Registry.register(Registries.BLOCK, id("crystal_glass"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(1.5f, 6).luminance(10)));
        CRYSTAL_BRICKS = Registry.register(Registries.BLOCK, id("crystal_bricks"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(10)));
        CRYSTAL_PILLAR = Registry.register(Registries.BLOCK, id("crystal_pillar"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(10)));
        CRYSTAL_LAMP = Registry.register(Registries.BLOCK, id("crystal_lamp"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(1.5f, 6).luminance(10)));
        CRYSTAL_CLUSTER = Registry.register(Registries.BLOCK, id("crystal_cluster"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(1.5f, 6).luminance(10)));
        VOID_STONE = Registry.register(Registries.BLOCK, id("void_stone"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        VOID_BRICKS = Registry.register(Registries.BLOCK, id("void_bricks"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        VOID_TILES = Registry.register(Registries.BLOCK, id("void_tiles"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        VOID_PILLAR = Registry.register(Registries.BLOCK, id("void_pillar"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        VOID_GLASS = Registry.register(Registries.BLOCK, id("void_glass"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(1.5f, 6).luminance(0)));
        VOID_LAMP = Registry.register(Registries.BLOCK, id("void_lamp"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(1.5f, 6).luminance(10)));
        ENDERITE_ORE = Registry.register(Registries.BLOCK, id("enderite_ore"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        RAW_ENDERITE_BLOCK = Registry.register(Registries.BLOCK, id("raw_enderite_block"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        ENDERITE_BLOCK = Registry.register(Registries.BLOCK, id("enderite_block"), new Block(FabricBlockSettings.copyOf(Blocks.END_STONE).strength(2.0f, 6).luminance(0)));
        VOID_ANCHOR = Registry.register(Registries.BLOCK, id("void_anchor"), new VoidAnchorBlock(FabricBlockSettings.copyOf(Blocks.OBSIDIAN).strength(6, 1200).luminance(5).nonOpaque()));
        ENDER_TELEPORTER = Registry.register(Registries.BLOCK, id("ender_teleporter"), new EnderTeleporterBlock(FabricBlockSettings.copyOf(Blocks.OBSIDIAN).strength(5, 600).luminance(8).nonOpaque()));
        Block[] blocks={ENDER_STONE,ENDER_SOIL,ENDER_GRASS,ENDER_MOSS,ENDER_MUD,ENDER_ROCK,ENDER_BRICKS,ENDER_TILES,CRACKED_ENDER_BRICKS,POLISHED_ENDER_STONE,ENDER_STONE_PILLAR,ENDER_STONE_SLAB,ENDER_STONE_STAIRS,ENDER_STONE_WALL,ENDER_LOG,STRIPPED_ENDER_LOG,ENDER_WOOD,STRIPPED_ENDER_WOOD,ENDER_PLANKS,ENDER_LEAVES,ENDER_SAPLING,ENDER_STAIRS,ENDER_SLAB,ENDER_FENCE,ENDER_FENCE_GATE,ENDER_DOOR,ENDER_TRAPDOOR,ENDER_BUTTON,ENDER_PRESSURE_PLATE,ENDER_SIGN,ENDER_HANGING_SIGN,END_CRYSTAL_BLOCK,CRYSTAL_GLASS,CRYSTAL_BRICKS,CRYSTAL_PILLAR,CRYSTAL_LAMP,CRYSTAL_CLUSTER,VOID_STONE,VOID_BRICKS,VOID_TILES,VOID_PILLAR,VOID_GLASS,VOID_LAMP,ENDERITE_ORE,RAW_ENDERITE_BLOCK,ENDERITE_BLOCK,VOID_ANCHOR,ENDER_TELEPORTER};
        for(Block b:blocks){Identifier key=Registries.BLOCK.getId(b);if(!Registries.ITEM.containsId(key))Registry.register(Registries.ITEM,key,new net.minecraft.item.BlockItem(b,new net.minecraft.item.Item.Settings()));}
    }
}
